version: '3.5'

services:
  db:
    image: mysql:5.7
    ports:
      - 3333:3333
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=egnytereg
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  flaskapp:
    build:
      context: .
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=egnyte_app.app
      - DATABASE_URI=mysql://root:password@db:3306/egnytereg
